CREATE FUNCTION AvaragePriceForPlatform(platform IN VARCHAR2)
  RETURN FLOAT 
  IS
    avarage FLOAT;
  BEGIN
	
      SELECT AVG(GP.PRICE) INTO avarage FROM GAME_PLAT GP WHERE GP.PLATFORM = platform GROUP BY GP.PLATFORM;
	
RETURN avarage;
END AvaragePriceForPlatform;

CREATE OR REPLACE PROCEDURE Sale(discount IN FLOAT DEFAULT 0, platform IN VARCHAR2)
IS
BEGIN
    
    UPDATE GAME_PLAT GP SET GP.PRICE = GP.PRICE*(1- discount) WHERE GP.PLATFORM = platform;
    
END Sale;

CREATE SEQUENCE GAMES_ID
MINVALUE 1
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE DEVS_ID
MINVALUE 100
START WITH 100
INCREMENT BY 1;

CREATE SEQUENCE REVIEW_ID
MINVALUE 1
START WITH 1
INCREMENT BY 1;