CREATE OR REPLACE FUNCTION AvaragePriceForPlatform(platform BIGINT)
  RETURNS FLOAT 
  AS '
  BEGIN
  DECLARE avarage FLOAT;
  BEGIN
	
      SELECT AVG(GP.PRICE) INTO avarage FROM GAME_PLAT GP WHERE GP.PLATFORM_ID = platform GROUP BY GP.PLATFORM_ID;
	
	RETURN avarage;
END;
END;'
LANGUAGE 'plpgsql';

CREATE OR REPLACE FUNCTION 
Sale(INOUT discount FLOAT,platform BIGINT)
AS '
BEGIN
    
    UPDATE GAME_PLAT SET PRICE = PRICE*discount WHERE PLATFORM_ID = platform;
    
END; '
LANGUAGE 'plpgsql';

CREATE SEQUENCE GAMES_ID
MINVALUE 1
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE DEVS_ID
MINVALUE 100
START WITH 100
INCREMENT BY 1;

CREATE SEQUENCE REVIEW_ID
MINVALUE 1
START WITH 1
INCREMENT BY 1;